### ISSUE TITLE
Library compatible with Adafruit PN532

### ISSUE THREAD

**Issue by carvalab** [Pascal66/PN532_Reader#1]
Hello, thanks for awesome work, what library is in use for this project?
The best from my point view is Adafruit PN532 [Adafruit-PN532](https://github.com/adafruit/Adafruit-PN532)

`#include <Adafruit_PN532.h>`

And edit nfc use compatible.. No more work for this...
Thanks.

**Comment by Pascal66** [comment]
I use only the generic Wire librarie and the one I've pushed
