### ISSUE TITLE
Library I2C_PN532.h

### ISSUE THREAD

**Issue by carvalab** [Pascal66/PN532_Reader#2]
Hello @Pascal66, I have read your posts, and I'm trying to download the library used by you in the PN532 reader, but I'm not finding it on the internet. Could you please tell me where can I look for it or if is it possible for you to upload it on GIthub please? 
Thanks in advance,
Pablo

**Comment by Pascal66** [comment]
I'll push it on github as soon as I retrieve it . I've not working on it since a long time.

**Comment by carvalab** [comment]
Thanks in advance, for you work with pn532, one problem only, libnfc no can read the tag, always send uid 01 00 00 00, second the mfoc launch error, "no tags found",  you know the solution?  Thanks

**Comment by Pascal66** [comment]
I know that's not working fully, there's many work to do
